# Generated by Django 2.1.5 on 2019-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song', models.CharField(max_length=100, null=True)),
                ('Artist', models.CharField(max_length=20, null=True)),
                ('Genre', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
