# Generated by Django 3.0 on 2019-12-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organised_on', models.DateTimeField(verbose_name='date published')),
                ('organising_head', models.CharField(max_length=100)),
                ('organising_budget', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
