# Generated by Django 2.1.5 on 2019-12-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Artist',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Genre',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Song',
            field=models.TextField(max_length=30),
        ),
    ]
