# Generated by Django 2.1.5 on 2019-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191224_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Artist',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Genre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Song',
            field=models.CharField(max_length=30),
        ),
    ]
