# Generated by Django 2.1.5 on 2019-12-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191224_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Id',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
